version: "3.8"

services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise_dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./flowise_data:/root/.flowise
